### ISSUE TITLE
make problem

### ISSUE THREAD

**Issue by fangxing123** [swarm-robotics/fordyca#434]
In file included from /home/robot/fordyca/include/fordyca/representation/arena_map.hpp:31:0,
                 from /home/robot/fordyca/include/fordyca/support/loop_functions_utils.hpp:33,
                 from /home/robot/fordyca/src/support/loop_functions_utils.cpp:24:
/home/robot/fordyca/include/fordyca/representation/arena_grid.hpp:29:36: fatal error: rcppsw/ds/grid2D_ptr.hpp: No such file or directory
compilation terminated.
CMakeFiles/fordyca.dir/build.make:950: recipe for target 'CMakeFiles/fordyca.dir/src/support/loop_functions_utils.cpp.o' failed
make[2]: *** [CMakeFiles/fordyca.dir/src/support/loop_functions_utils.cpp.o] Error 1
CMakeFiles/Makefile2:133: recipe for target 'CMakeFiles/fordyca.dir/all' failed
make[1]: *** [CMakeFiles/fordyca.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jharwell** [comment]
Are you on the devel branch or the master branch for the rcppsw and fordyca repos?

**Comment by fangxing123** [comment]
rcppsw and fordyca are both on the devel branch

**Comment by jharwell** [comment]
Oh I see--I pushed changes to rcppsw for #426, but not for fordyca yet. I should have that done in an hour or so, and then you should be good to go.

**Comment by fangxing123** [comment]
Thanks a lot.

**Comment by jharwell** [comment]
Should be good to go if you pull from both repos on the devel branch! Let me know if it works for you, and I will close the issue.

**Comment by fangxing123** [comment]
I can't  run the demo experiment.I can't figure out the reason.
single-source.argos 
This one can run,but i can't see the visual interface.
randomized.argos
[FATAL] Error initializing loop functions
[FATAL] Symbol "depth0_foraging_loop_functions" not found
benchmark-single-source.argos
[FATAL] Failed to initialize the simulator. Parse error inside the <framework> tag.
[FATAL] Error parsing attribute "length"
Could not convert "__0__" to target type <ticpp.h@200>

**Comment by jharwell** [comment]
single-source.argos is the main file I've been testing with, so use/modify that one as needed. randomized.argos is much older and should probably be deleted.

You can't see the visualization because it is currently disabled because I have been running optimized builds with threading which crash if visualization is enabled. You can re-enable it by uncommenting the `<visualization>' tag in the file.

**Comment by jharwell** [comment]
If you are looking to run more nuanced/scalable experiments, take a look at the `sierra` repo, which does automatic input file generation, experiment running, results averaging, and graph generation.

**Comment by fangxing123** [comment]
/home/robot/fordyca/src/metrics/robot_interaction_metrics_collector.cpp: In member function ‘virtual bool fordyca::metrics::robot_interaction_metrics_collector::csv_line_build(std::__cxx11::string&)’:
/home/robot/fordyca/src/metrics/robot_interaction_metrics_collector.cpp:67:32: error: ‘class rcppsw::swarm::interactivity’ has no member named ‘raw_degree’
   line += std::to_string(m_cum.raw_degree(tmp)) + separator();
                                ^~~~~~~~~~
/home/robot/fordyca/src/metrics/robot_interaction_metrics_collector.cpp:68:32: error: ‘class rcppsw::swarm::interactivity’ has no member named ‘normed_degree’
   line += std::to_string(m_cum.normed_degree(tmp)) + separator();
                                ^~~~~~~~~~~~~
CMakeFiles/fordyca.dir/build.make:182: recipe for target 'CMakeFiles/fordyca.dir/src/metrics/robot_interaction_metrics_collector.cpp.o' failed
make[2]: *** [CMakeFiles/fordyca.dir/src/metrics/robot_interaction_metrics_collector.cpp.o] Error 1
CMakeFiles/Makefile2:231: recipe for target 'CMakeFiles/fordyca.dir/all' failed
make[1]: *** [CMakeFiles/fordyca.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by fangxing123** [comment]
This happened after I pulled it yesterday

**Comment by fangxing123** [comment]
rcppsw  8b579a5374d081076bbf3fa50b11fd57ce52d503
fordyca  2c00938e6a639b84e5064f0c780f1784be444d80

**Comment by fangxing123** [comment]
After i pull the newest version of rcppsw/fordyca,it works well.Thanks a lot

**Comment by fangxing123** [comment]
Excuse me,when i run .argos file ,it always stop at "Attribute does not exist <ticpp.h@1791>" .Can you heip me fix it?Thanks a lot.

**Comment by jharwell** [comment]
I cannot without additional information. What attribute? What branch/sha1 are you running in rcppsw/fordyca?

**Comment by fangxing123** [comment]
I have pulled the newest version of rcppsw/fordyca on devel branch today,and it still stop at "Attribute does not exist ticpp.h@1791".This information comes out when I run demo.argos.

[INFO] Loaded library "/home/robot/fordyca/build/lib/libfordyca.so"
[INFO] Loaded library "/home/robot/fordyca/build/lib/libticpp.so"
[INFO] Loaded library "/usr/local/lib/argos3/libargos3plugin_simulator_entities.so"
[INFO] Loaded library "/usr/local/lib/argos3/libargos3plugin_simulator_dynamics2d.so"
[INFO] Loaded library "/usr/local/lib/argos3/libargos3core_simulator.so"
[INFO] Loaded library "/usr/local/lib/argos3/libargos3plugin_simulator_footbot.so"
[INFO] Loaded library "/usr/local/lib/argos3/libargos3plugin_simulator_prototype.so"
[INFO] Loaded library "/usr/local/lib/argos3/libargos3plugin_simulator_genericrobot.so"
[INFO] Loaded library "/usr/local/lib/argos3/libargos3plugin_simulator_pointmass3d.so"
[INFO] Loaded library "/usr/local/lib/argos3/libargos3plugin_simulator_qtopengl.so"
[INFO] Loaded library "/usr/local/lib/argos3/libargos3plugin_simulator_dynamics3d.so"
[INFO] Loaded library "/usr/local/lib/argos3/libargos3plugin_simulator_eyebot.so"
[INFO] Loaded library "/usr/local/lib/argos3/libargos3plugin_simulator_epuck.so"
[INFO] Loaded library "/usr/local/lib/argos3/libargos3plugin_simulator_spiri.so"
[INFO] Loaded library "/usr/local/lib/argos3/libargos3plugin_simulator_media.so"
[INFO] Not using threads
[INFO] Using random seed = 123
[INFO] Using simulation clock tick = 0.2
[INFO] Total experiment length in clock ticks = 50000
[INFO] Loaded library "/home/robot/fordyca/build/lib/libfordyca.so"
[INFO] Loaded library "/home/robot/fordyca/build/lib/libfordyca.so"
[INFO] The physics engine "dyn2d0" will perform 10 iterations per tick (dt = 0.02 sec)
Attribute does not exist <ticpp.h@1791>

**Comment by fangxing123** [comment]
This is my demo.argos.
[demo .txt](https://github.com/swarm-robotics/fordyca/files/2701454/demo.txt)

**Comment by jharwell** [comment]
The demo.argos and my testing.argos got out of sync. Fixed by #501 and merged to devel.
